name: Build

on:
    pull_request:
      branches: [ 'main', 'master' ]
      types:
      - opened
      - synchronize
      - reopened
      - closed
      paths:
      - 'docs/**'
env:
    http_proxy: ###
    https_proxy: ####
    no_proxy: #####
jobs:
    build:
      uses: intel-innersource/applications.services.esh.intel-edge-services-document/.github/workflows/build.yml@main
      secrets: inherit          
