   name: PublishToAWS
   on:
    workflow_dispatch:
   env:
      # proxy-dmz mangles DNS resolution, resulting in certificate verification failure
      http_proxy: ####
      https_proxy: ####
      no_proxy: ####

   jobs:
      build:
        uses: intel-innersource/applications.services.esh.intel-edge-services-document/.github/workflows/publishtoaws.yml@main
        secrets: inherit
